nelmio_cors:
  defaults:
    allow_credentials: false
    allow_headers: [ 'Content-Type', 'Authorization' ]
    allow_methods: [ 'GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE' ]
    allow_origin: [ '%env(CORS_ALLOW_ORIGIN)%' ]
    expose_headers: [ 'Link' ]
    max_age: 0
    origin_regex: true
  paths:
    '^/': null
