controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authentication_token:
  path: /authentication_token
  methods: [ 'POST' ]

refresh_token:
  path: /refresh_token
  methods: [ 'POST' ]

token_invalidate:
  path: /token_invalidate
  methods: [ 'POST' ]
