model_names = [
    "Convolutional Neural Network",
    "Decision Tree",
    "K-Nearest Neighbors",
    "Long Short-Term Memory",
    "Naive Bayes",
    "Neural Network",
    "Random Forest",
    "Recurrent Neural Network",
    "Support Vector Machine",
    "XGBoost",
    "Gradient Boosting Machine",
    "AdaBoost",
    "Bagging",
    "Multilayer Perceptron",
    "Autoencoder",
    "Generative Adversarial Network",
    "Restricted Boltzmann Machine",
    "Principal Component Analysis",
    "Linear Discriminant Analysis",
    "Quadratic Discriminant Analysis",
    "Logistic Regression",
    "Elastic Net",
    "Ridge Regression",
    "Lasso Regression",
    "Polynomial Regression",
    "Decision Stump",
    "Extra Trees",
    "Isolation Forest",
    "LightGBM",
    "CatBoost",
    "H2O.ai",
    "Deep Belief Network",
    "Markov Chain",
    "Hidden Markov Model",
    "Bayesian Network",
    "Support Vector Regression",
    "Ordinary Least Squares Regression",
    "K-Means Clustering",
    "Hierarchical Clustering",
    "DBSCAN",
    "Gaussian Mixture Model",
    "Latent Dirichlet Allocation",
    "Factorization Machines",
    "Collaborative Filtering",
    "Matrix Factorization",
    "Singular Value Decomposition",
    "t-Distributed Stochastic Neighbor Embedding",
    "UMAP",
    "Self-Organizing Map",
    "Neural Turing Machine",
    "Transformers",
    "Bidirectional Encoder Representations from Transformers",
    "Reinforcement Learning Models",
    "Meta-Learning Algorithms",
    "Neural Architecture Search",
    "Evolutive Algorithms",
    "Simulated Annealing",
    "Particle Swarm Optimization",
    "Ant Colony Optimization",
    "Fuzzy Logic Systems",
]

model_types = [
    "Anomaly Detection",
    "Association Rule Learning",
    "Classification",
    "Clustering",
    "Computer Vision",
    "Deep Learning",
    "Dimensionality Reduction",
    "Natural Language Processing",
    "Regression",
    "Reinforcement Learning",
    "Ensemble Learning",
    "Semi-Supervised Learning",
    "Self-Supervised Learning",
    "Unsupervised Learning",
    "Supervised Learning",
    "Graph-Based Learning",
    "Time Series Forecasting",
    "Recommendation Systems",
    "Transfer Learning",
    "Bayesian Optimization",
    "Metric Learning",
    "Sparse Learning",
    "Federated Learning",
    "Few-Shot Learning",
    "Zero-Shot Learning",
    "Multitask Learning",
    "Active Learning",
    "Causal Inference",
    "Generative Models",
    "Physics-Informed Machine Learning",
    "Explainable AI (XAI)",
    "Meta-Learning",
    "Attention Mechanisms",
    "Neuro-Symbolic Learning",
    "Adversarial Learning",
    "Imitation Learning",
    "Manifold Learning",
    "Representation Learning",
    "Probabilistic Modeling",
    "Constraint-Based Learning",
    "Multi-Agent Learning",
    "Evolutionary Algorithms",
    "Stochastic Processes",
    "Quantum Machine Learning",
    "Hybrid Models",
]
